version: '3.5'

services:
  ticketing-mysql:
    environment:
      MYSQL_RANDOM_ROOT_PASSWORD: "yes"
      MYSQL_ONETIME_PASSWORD: "yes"
      MYSQL_DATABASE: "callsign-test-app"
      MYSQL_USER:     "new-root"
      MYSQL_PASSWORD: "new-root"
    ports:
      - "3309:3306"
    build:
      context: ./
      dockerfile: ./Dockerfile